--feel free to modify the defaultProperties table, add your own properties and change whathever you want!

local defaultProperties = {
    ScreenGui = {
        ResetOnSpawn = false,
        IgnoreGuiInset = true
    },
    SurfaceGui = {
        ResetOnSpawn = false,
        AlwaysOnTop = false
    },
    BillboardGui = {
        ResetOnSpawn = false,
        AlwaysOnTop = false
    },
    Frame = {

    },
    ScrollingFrame = {
        CanvasSize = UDim2.new(0,0,1,0),
        AutomaticCanvasSize = Enum.AutomaticSize.XY
    },
    ViewportFrame = {

    },
    VideoFrame = {

    },
    TextBox = {
        TextScaled = true
    },
    TextButton = {
        TextScaled = true
    },
    TextLabel = {
        TextScaled = true
    },
    ImageLabel = {

    },
    ImageButton = {

    },
    CanvasGroup = {

    },
    Path2D = {

    }
}

return defaultProperties